name: Audit

on:
  schedule:
    - cron: "23 6 * * 1"
  workflow_dispatch:

jobs:
  audit:
    name: NPM Audit
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: npm

      - run: npm ci
      - run: npm audit --omit=dev --audit-level=high
